// PREMINUMMODULE
export const GET_ADMINDATA = "GET_ADMINDATA";
export const ADD_ADMINDATA = "ADD_ADMINDATA";
export const REMOVE_ADMINDATA = "REMOVE_ADMINDATA";
export const UPDATE_ADMINDATA = "UPDATE_ADMINDATA";

export const GET_USERDATA = "GET_UESRDATA";
export const ADD_USERDATA = "ADD_USERDATA";
export const REMOVE_USERDATA = "REMOVE_USERDATA";
export const UPDATE_USERDATA = "UPDATE_USERDATA";

export const UPADTE_CHARTOPTION_PREMINUM = "UPADTE_CHARTOPTION_PREMINUM";

// RESOURCEMODULE
export const UPDATE_CHARTOPTION_RESOURCE = "UPADTE_CHARTOPTION_RESOURCE";

// TASKMODULE
export const UPDATE_CHARTOPTION_TASK = "UPADTE_CHARTOPTION_TASK";

// ROBOTMODULE
export const UPDATE_CHARTOPTION_ROBOT = "UPADTE_CHARTOPTION_ROBOT";
